services:
  glances:
    image: nicolargo/glances:latest
    container_name: glances
    pid: host
    ports:
      - "61208:61208"
      - "61209:61209"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - GLANCES_OPT=-w
    restart: unless-stopped
